import {useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {driversApi} from '../services/drivers-api';
import {ApiError} from '../services/api';
import {useAuth} from '../hooks/useAuth';
import type {Driver,DriverPage,DriverValues} from '../types/drivers';
import {DriverForm} from '../features/drivers/DriverForm';
export function DriversPage(){
 const {id}=useParams();const navigate=useNavigate();const {acceptSession}=useAuth();const [data,setData]=useState<DriverPage>();const [driver,setDriver]=useState<Driver>();const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [attempt,setAttempt]=useState(0);const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [term,setTerm]=useState('');const [estado,setEstado]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const editing=location.pathname.endsWith('/editar');const creating=location.pathname.endsWith('/nuevo');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setDriver(undefined);
 (creating?Promise.resolve(undefined):id?driversApi.get(id,controller.signal):driversApi.list(page,term,estado,controller.signal)).then(result=>{if(controller.signal.aborted)return;if(result&&'items' in result)setData(result);else setDriver(result as Driver|undefined);}).catch((e:unknown)=>{if(controller.signal.aborted)return;if(e instanceof ApiError&&e.status===401)acceptSession(null);else setError(e instanceof Error?e.message:'No se pudo cargar conductores.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[id,creating,page,term,estado,attempt,acceptSession]);
 async function save(values:DriverValues){try{if(id)await driversApi.update(id,values);else await driversApi.create(values);setNotice('Conductor guardado correctamente.');navigate('/conductores');setAttempt(a=>a+1);}catch(e){if(e instanceof ApiError&&e.status===401)acceptSession(null);throw e;}}
 async function toggle(){if(!driver)return;setBusy(true);setError('');try{setDriver(await driversApi.update(driver.conductor_id,{estado:driver.estado==='ACTIVO'?'INACTIVO':'ACTIVO'}));setNotice('Estado administrativo actualizado.');}catch(e){if(e instanceof ApiError&&e.status===401)acceptSession(null);else setError(e instanceof Error?e.message:'No se pudo cambiar el estado.');}finally{setBusy(false);}}
 return <section className="users-panel"><div className="page-heading"><h1>{creating?'Registrar conductor':editing?'Editar conductor':id?'Consultar conductor':'Conductores'}</h1>{!id&&!creating?<Link className="button button-primary" to="/conductores/nuevo">Registrar conductor</Link>:<Link to="/conductores">Volver a conductores</Link>}</div>
 {notice&&<p role="status">{notice}</p>}{!id&&!creating&&<form className="driver-filters" onSubmit={e=>{e.preventDefault();setPage(1);setTerm(search);setAttempt(a=>a+1);}}><label>Buscar nombre o DNI<input value={search} maxLength={150} onChange={e=>setSearch(e.target.value)}/></label><label>Filtrar estado<select value={estado} onChange={e=>{setEstado(e.target.value);setPage(1);}}><option value="">Todos</option><option>ACTIVO</option><option>INACTIVO</option></select></label><button className="button button-secondary">Buscar</button></form>}
 {loading?<p role="status">Cargando conductores…</p>:error?<><p role="alert">{error}</p><button className="button button-secondary" onClick={()=>setAttempt(a=>a+1)}>Reintentar</button></>:creating||editing?<DriverForm key={id??'new'} initial={driver} onSave={save}/>:driver?<><dl className="driver-detail">{Object.entries({Nombre:driver.nombre_completo,DNI:driver.dni,'Categoría de licencia':driver.licencia_categoria,'Años de experiencia':driver.anios_experiencia,Teléfono:driver.telefono,Estado:driver.estado,'Cuenta vinculada':driver.usuario_id??'Sin cuenta'}).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="driver-actions"><Link className="button button-primary" to={'/conductores/'+driver.conductor_id+'/editar'}>Editar conductor</Link><button disabled={busy} className="button button-secondary" onClick={toggle}>{busy?'Actualizando…':driver.estado==='ACTIVO'?'Desactivar conductor':'Activar conductor'}</button></div></>:data?<><p>{data.total} conductores registrados</p>{!data.items.length?<p>No hay conductores para esta consulta.</p>:<div className="table-scroll" role="region" aria-label="Listado de conductores" tabIndex={0}><table><thead><tr><th>Nombre</th><th>DNI</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{data.items.map(d=><tr key={d.conductor_id}><td>{d.nombre_completo}</td><td>{d.dni}</td><td>{d.estado}</td><td><Link to={'/conductores/'+d.conductor_id}>Consultar</Link> · <Link to={'/conductores/'+d.conductor_id+'/editar'}>Editar</Link></td></tr>)}</tbody></table></div>}<div className="driver-actions"><button className="button button-secondary" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page}</span><button className="button button-secondary" disabled={page*20>=data.total} onClick={()=>setPage(p=>p+1)}>Siguiente</button></div></>:null}</section>;
}
