import { FormEvent, useEffect, useState } from 'react';
import { ApiError } from '../services/api';
import { vehiclesApi } from '../services/vehicles-api';
import { VEHICLE_STATES, Vehicle, VehicleValues } from '../types/vehicles';
import { ErrorMessage } from '../components/ui/ErrorMessage';
const empty: VehicleValues = { placa: '', tipo: '', capacidad_carga_kg: 0, capacidad_volumen_m3: null, consumo_km_l: 0, factor_emision_kg_co2_km: 0, anio_fabricacion: new Date().getFullYear(), estado: 'DISPONIBLE' };
export function VehiclesPage() {
  const [items, setItems] = useState<Vehicle[]>([]); const [form, setForm] = useState<VehicleValues>(empty); const [editing, setEditing] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = () => vehiclesApi.list().then(setItems).catch(() => setError('No se pudieron consultar los vehículos.'));
  useEffect(() => { load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setMessage(''); try { const result = editing ? await vehiclesApi.update(editing, form) : await vehiclesApi.create(form); setItems(current => editing ? current.map(item => item.vehiculo_id === editing ? result : item) : [...current, result].sort((a, b) => a.placa.localeCompare(b.placa))); setForm(empty); setEditing(''); setMessage(editing ? 'Vehículo actualizado correctamente.' : 'Vehículo registrado correctamente.'); } catch (cause: unknown) { setError(cause instanceof ApiError && cause.status === 409 ? 'La placa ya está registrada.' : 'No se pudo guardar el vehículo.'); } };
  const edit = (vehicle: Vehicle) => { setEditing(vehicle.vehiculo_id); setForm({ placa: vehicle.placa, tipo: vehicle.tipo, capacidad_carga_kg: Number(vehicle.capacidad_carga_kg), capacidad_volumen_m3: vehicle.capacidad_volumen_m3 === null ? null : Number(vehicle.capacidad_volumen_m3), consumo_km_l: Number(vehicle.consumo_km_l), factor_emision_kg_co2_km: Number(vehicle.factor_emision_kg_co2_km), anio_fabricacion: vehicle.anio_fabricacion, estado: vehicle.estado }); };
  const field = (name: keyof VehicleValues, label: string, type = 'text') => <div className="form-field"><label htmlFor={`vehicle-${name}`}>{label}</label><input id={`vehicle-${name}`} required={name !== 'capacidad_volumen_m3' && name !== 'estado'} type={type} value={form[name] ?? ''} onChange={event => setForm({ ...form, [name]: type === 'number' ? Number(event.target.value) : event.target.value })} /></div>;
  return <section className="users-panel"><div className="page-heading"><h1>Gestionar vehículos</h1></div>{error && <ErrorMessage message={error} />}{message && <p role="status">{message}</p>}<form onSubmit={submit}><div className="form-grid">{field('placa', 'Placa')}{field('tipo', 'Tipo')}{field('capacidad_carga_kg', 'Capacidad de carga (kg)', 'number')}{field('capacidad_volumen_m3', 'Capacidad de volumen (m³)', 'number')}{field('consumo_km_l', 'Consumo (km/l)', 'number')}{field('factor_emision_kg_co2_km', 'Emisión (kg CO₂/km)', 'number')}{field('anio_fabricacion', 'Año de fabricación', 'number')}<div className="form-field"><label htmlFor="vehicle-estado">Estado operativo</label><select id="vehicle-estado" value={form.estado} onChange={event => setForm({ ...form, estado: event.target.value as VehicleValues['estado'] })}>{VEHICLE_STATES.map(state => <option key={state}>{state}</option>)}</select></div></div><button className="button button-primary" type="submit">{editing ? 'Guardar cambios' : 'Registrar vehículo'}</button>{editing && <button className="button button-secondary" type="button" onClick={() => { setEditing(''); setForm(empty); }}>Cancelar</button>}</form><div className="table-scroll"><table><caption className="sr-only">Vehículos registrados</caption><thead><tr><th>Placa</th><th>Tipo</th><th>Capacidad (kg)</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{items.map(item => <tr key={item.vehiculo_id}><td>{item.placa}</td><td>{item.tipo}</td><td>{item.capacidad_carga_kg}</td><td>{item.estado}</td><td><button className="table-action" type="button" onClick={() => edit(item)}>Editar</button></td></tr>)}</tbody></table></div></section>;
}
