import {test,expect,type Page} from '@playwright/test';
const id='00000000-0000-4000-8000-000000000001';
async function mock(page:Page,origin:string,role='Administrador'){
 let driver={conductor_id:id,nombre_completo:'Fixture conductor',dni:'fixture',licencia_categoria:'fixture',telefono:'fixture',anios_experiencia:0,usuario_id:null,estado:'ACTIVO'};
 const headers={'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Credentials':'true'};
 await page.route('**/auth/me',r=>r.fulfill({headers,json:{usuario_id:id,email:'fixture@example.com',rol:{nombre:role},expiresAt:Date.now()+900000}}));
 await page.route('**/drivers**',async r=>{const req=r.request();if(req.method()==='OPTIONS')return r.fulfill({status:204,headers:{...headers,'Access-Control-Allow-Methods':'GET,POST,PATCH','Access-Control-Allow-Headers':'Content-Type'}});
 if(req.method()==='POST'||req.method()==='PATCH'){driver={...driver,...req.postDataJSON()};return r.fulfill({status:req.method()==='POST'?201:200,headers,json:driver});}
 return r.fulfill({headers,json:new URL(req.url()).pathname==='/drivers'?{items:[driver],total:1,page:1,pageSize:20}:driver});});
 await page.route('**/admin/summary',r=>r.fulfill({headers,json:{totalOrders:0,pendingOrders:0,totalUsers:0,ordersByState:[]}}));
}
for(const width of [390,768,1366,1440])test('Conductores responsive '+width,async({page,baseURL})=>{await page.setViewportSize({width,height:900});await mock(page,new URL(baseURL!).origin);await page.goto('/conductores');await expect(page.getByRole('heading',{name:'Conductores',exact:true})).toBeVisible();if(width<1024)await page.getByRole('button',{name:'Abrir menú'}).click();await expect(page.getByRole('link',{name:'Conductores',exact:true})).toBeVisible();if(width<1024)await page.getByRole('button',{name:'Cerrar menú'}).click();await expect(page.getByText('Fixture conductor')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('registro, edición, consulta y estado con API simulada',async({page,baseURL})=>{await mock(page,new URL(baseURL!).origin,'Operador / Técnico');await page.goto('/conductores/nuevo');for(const [label,value] of [['Nombre completo','Fixture conductor'],['DNI','fixture'],['Categoría de licencia','fixture'],['Teléfono','fixture']])await page.getByLabel(label,{exact:true}).fill(value);await page.getByRole('button',{name:'Guardar conductor'}).click();await expect(page).toHaveURL(/\/conductores$/);await page.getByRole('link',{name:'Consultar',exact:true}).click();await page.getByRole('button',{name:'Desactivar conductor'}).click();await expect(page.getByRole('button',{name:'Activar conductor'})).toBeVisible();await page.getByRole('link',{name:'Editar conductor',exact:true}).click();await page.getByLabel('Nombre completo').fill('Fixture editado');await page.getByRole('button',{name:'Guardar conductor'}).click();await expect(page.getByText('Fixture editado')).toBeVisible();});
for(const role of ['Usuario Final / Conductor','Auditor Externo'])test('sin permisos '+role,async({page,baseURL})=>{await mock(page,new URL(baseURL!).origin,role);await page.goto('/conductores');await expect(page).toHaveURL(/\/acceso\//);await expect(page.getByRole('link',{name:'Conductores',exact:true})).toHaveCount(0);});
test('login sirve paisaje original en Docker',async({page})=>{await page.goto('/login');const bg=await page.locator('.login-background').evaluate(e=>getComputedStyle(e).backgroundImage);expect(bg).not.toBe('none');const response=await page.request.get(bg.slice(5,-2));expect(response.status()).toBe(200);expect(response.headers()['content-type']).toContain('image/png');expect((await response.body()).length).toBeGreaterThan(1900000);});
