import { test, expect } from '@playwright/test';
import { createHmac } from 'node:crypto';
const apiUrl = process.env.E2E_API_URL ?? 'http://localhost:3000';
test('US-001 / US-002: login, F5, cierre explícito y rutas protegidas', async ({ page, context }, info) => {
  const email = process.env.E2E_LOGIN_EMAIL;
  const password = process.env.E2E_LOGIN_PASSWORD;
  if (!email || !password) throw new Error('Configura una cuenta de prueba mediante E2E_LOGIN_EMAIL y E2E_LOGIN_PASSWORD.');
  await page.goto('/acceso/administrador');
  await expect(page.getByRole('heading', { name: 'Acceso al sistema' })).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('login.png'), fullPage: true });
  await expect(page.getByLabel('Correo electrónico')).toHaveAttribute('type', 'email');
  const width = await page.evaluate(() => ({ viewport: window.innerWidth, document: document.documentElement.scrollWidth }));
  expect(width.document).toBeLessThanOrEqual(width.viewport);
  const button = await page.getByRole('button', { name: /Iniciar sesión/ }).boundingBox();
  expect(button?.height).toBeGreaterThanOrEqual(48);
  await page.getByLabel('Correo electrónico').fill(email);
  await page.getByLabel('Contraseña', { exact: true }).fill('wrong-password-for-test');
  await page.getByRole('button', { name: /Iniciar sesión/ }).click();
  await expect(page.getByRole('alert')).toHaveText('Credenciales incorrectas o usuario no habilitado.');
  await page.getByLabel('Contraseña', { exact: true }).fill(password);
  await page.getByRole('button', { name: /Iniciar sesión/ }).click();
  await expect(page).toHaveURL(/\/acceso\/administrador$/);
  await expect(page.getByRole('heading', { name: /^(Panel de administración|Acceso permitido)$/ })).toBeVisible();
  await expect(page.getByText(email, { exact: true })).toBeVisible();
  const storage = await page.evaluate(() => ({ local: localStorage.length, session: sessionStorage.length }));
  expect(storage).toEqual({ local: 0, session: 0 });
  await page.reload();
  await expect(page).toHaveURL(/\/acceso\/administrador$/);
  await expect(page.getByRole('heading', { name: /^(Panel de administración|Acceso permitido)$/ })).toBeVisible();
  const cookies = await context.cookies(`${apiUrl}/auth/me`);
  const session = cookies.find((cookie) => cookie.name === 'distrirapido_session_v2');
  expect(Boolean(session?.httpOnly)).toBe(true);
  expect(session?.sameSite).toBe('Lax');
  expect(await page.evaluate(() => document.cookie.includes('distrirapido_session_v2'))).toBe(false);
  const me = await context.request.get(`${apiUrl}/auth/me`); expect(me.status()).toBe(200);
  // Un fallo de red no debe simular que se eliminó la cookie HttpOnly.
  await page.route('**/auth/logout', (route) => route.abort());
  await page.getByRole('button', { name: 'Cerrar sesión' }).click();
  await expect(page.getByRole('alert')).toContainText('No se pudo cerrar la sesión');
  await expect(page).toHaveURL(/\/acceso\/administrador$/);
  await page.unroute('**/auth/logout');
  const logoutResponse = page.waitForResponse((response) => response.url().endsWith('/auth/logout') && response.status() === 204);
  await page.getByRole('button', { name: 'Cerrar sesión' }).click();
  await logoutResponse;
  await expect(page).toHaveURL(/\/login$/);
  await expect(page.getByRole('heading', { name: 'Acceso al sistema' })).toBeVisible();
  expect((await context.cookies()).some((cookie) => cookie.name === 'distrirapido_session_v2')).toBe(false);
  expect((await context.request.get(`${apiUrl}/auth/me`)).status()).toBe(401);
  await page.goto('/acceso/administrador');
  await expect(page).toHaveURL(/\/login$/);
  await page.reload(); await expect(page.getByRole('heading', { name: 'Acceso al sistema' })).toBeVisible();
  test.info().annotations.push({ type: 'viewport', description: info.project.name });
});

test('US-002: cookie inválida o JWT expirado bloquean restauración', async ({ page, context }) => {
  await context.addCookies([{ name: 'distrirapido_session_v2', value: 'tampered', domain: 'localhost', path: '/auth', httpOnly: true, sameSite: 'Lax' }]);
  await page.goto('/acceso/administrador'); await expect(page).toHaveURL(/\/login$/);
  const secret = process.env.JWT_SECRET;
  if (!secret) throw new Error('Configura JWT_SECRET del backend de pruebas para verificar expiración real.');
  const login = await context.request.post(`${apiUrl}/auth/login`, { data: { email: process.env.E2E_LOGIN_EMAIL, password: process.env.E2E_LOGIN_PASSWORD } });
  expect(login.status()).toBe(200);
  const identity = await login.json() as { user: { usuario_id: string } };
  const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url');
  const payload = Buffer.from(JSON.stringify({ sub: identity.user.usuario_id, iss: 'distrirapido', aud: 'distrirapido-web', exp: Math.floor(Date.now() / 1000) - 1 })).toString('base64url');
  const signature = createHmac('sha256', secret).update(`${header}.${payload}`).digest('base64url');
  await context.addCookies([{ name: 'distrirapido_session_v2', value: `${header}.${payload}.${signature}`, domain: 'localhost', path: '/auth', httpOnly: true, sameSite: 'Lax' }]);
  expect((await context.request.get(`${apiUrl}/auth/me`)).status()).toBe(401);
  await page.goto('/acceso/administrador'); await expect(page).toHaveURL(/\/login$/);
  await expect(page.getByRole('heading', { name: 'Acceso al sistema' })).toBeVisible();
});
