import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import '@fontsource/outfit/latin-600.css';
import '@fontsource/outfit/latin-700.css';
import './styles/tokens.css';
import './styles/app.css';
import { AuthProvider } from './features/auth/AuthProvider';
import { AppRoutes } from './routes/AppRoutes';
createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><AuthProvider><AppRoutes /></AuthProvider></BrowserRouter></StrictMode>);
