import 'reflect-metadata';
import {Test} from '@nestjs/testing';
import {INestApplication,ExecutionContext} from '@nestjs/common';
import {Prisma} from '@prisma/client';
import {plainToInstance} from 'class-transformer';
import {validate} from 'class-validator';
import request from 'supertest';
import {DriversModule} from './drivers.module';
import {DriversService} from './drivers.service';
import {DriversGuard} from './drivers.guard';
import {PrismaService} from '../prisma/prisma.service';
import {JwtAuthGuard} from '../auth/jwt-auth.guard';
import {ConfigModule,ConfigService} from '@nestjs/config';
import {configureApp} from '../common/configure-app';
import {CreateDriverDto,UpdateDriverDto,DriverQueryDto} from './dto/driver.dto';
const id='00000000-0000-4000-8000-000000000001';
const values={nombre_completo:'Fixture',dni:'fixture',licencia_categoria:'fixture',telefono:'fixture',anios_experiencia:0};
const record={...values,conductor_id:id,usuario_id:null,estado:'ACTIVO'};
const tx={conductor:{create:jest.fn(),update:jest.fn(),findUnique:jest.fn()},usuario:{findUnique:jest.fn()}};
const prisma={conductor:{findMany:jest.fn(),count:jest.fn(),findUnique:jest.fn()},$transaction:jest.fn()};
const service=new DriversService(prisma as unknown as PrismaService);
beforeEach(()=>{jest.resetAllMocks();tx.conductor.create.mockResolvedValue(record);tx.conductor.update.mockResolvedValue({...record,estado:'INACTIVO'});tx.conductor.findUnique.mockResolvedValue(record);prisma.conductor.findUnique.mockResolvedValue(record);prisma.conductor.findMany.mockResolvedValue([record]);prisma.conductor.count.mockResolvedValue(25);prisma.$transaction.mockImplementation((arg:unknown)=>typeof arg==='function'?arg(tx):Promise.all(arg as Promise<unknown>[]));});
it('alta sin cuenta y sin crear usuario',async()=>{await expect(service.create(values)).resolves.toEqual(record);expect(tx.usuario.findUnique).not.toHaveBeenCalled();expect(tx.conductor.create).toHaveBeenCalledWith({data:{...values,estado:'ACTIVO'}});});
it('listado usa count completo con paginación',async()=>{expect(await service.list({page:2,pageSize:20})).toMatchObject({total:25,page:2});expect(prisma.conductor.findMany).toHaveBeenCalledWith(expect.objectContaining({skip:20,take:20}));});
it('permite cuenta con rol técnico de conductor',async()=>{tx.usuario.findUnique.mockResolvedValue({rol:{nombre:'Usuario Final / Conductor'}});await service.create({...values,usuario_id:id});expect(tx.conductor.create).toHaveBeenCalled();});
it.each([null,{rol:{nombre:'Administrador'}}])('rechaza cuenta ajena sin escribir %j',async user=>{tx.usuario.findUnique.mockResolvedValue(user);await expect(service.create({...values,usuario_id:id})).rejects.toThrow('rol');expect(tx.conductor.create).not.toHaveBeenCalled();});
it('PATCH estado conserva datos restantes y permite desvincular',async()=>{await service.update(id,{estado:'INACTIVO',usuario_id:null});expect(tx.conductor.update).toHaveBeenCalledWith({where:{conductor_id:id},data:{estado:'INACTIVO',usuario_id:null}});});
it('rechaza PATCH vacío y conductor inexistente',async()=>{await expect(service.update(id,{})).rejects.toThrow('campo');tx.conductor.findUnique.mockResolvedValue(null);await expect(service.update(id,{estado:'ACTIVO'})).rejects.toThrow('no encontrado');});
it.each([['P2002',409],['P2003',400],['P2025',404],['P2021',503],['P2022',503]])('traduce error Prisma %s',async(code,status)=>{tx.conductor.create.mockRejectedValue(new Prisma.PrismaClientKnownRequestError('fixture',{code:code as string,clientVersion:'6.12.0'}));await expect(service.create(values)).rejects.toMatchObject({status});});
it.each([{estado:'DISPONIBLE'},{estado:null},{anios_experiencia:null},{usuario_id:'bad'}])('PATCH rechaza %j',async change=>{expect((await validate(plainToInstance(UpdateDriverDto,change))).length).toBeGreaterThan(0);});
it('alta permite UUID nulo, consulta rechaza paginación inválida',async()=>{expect(await validate(plainToInstance(CreateDriverDto,{...values,usuario_id:null}))).toHaveLength(0);expect((await validate(plainToInstance(DriverQueryDto,{page:'0'}))).length).toBeGreaterThan(0);});
it.each(['Usuario Final / Conductor','Auditor Externo'])('guard bloquea %s',role=>{const context={switchToHttp:()=>({getRequest:()=>({user:{rol:{nombre:role}}})})};expect(()=>new DriversGuard().canActivate(context as ExecutionContext)).toThrow('permisos');});
describe('HTTP sin PostgreSQL real',()=>{let app:INestApplication;beforeAll(async()=>{const module=await Test.createTestingModule({imports:[ConfigModule.forRoot({isGlobal:true,ignoreEnvFile:true}),DriversModule]}).overrideProvider(PrismaService).useValue(prisma).overrideProvider(ConfigService).useValue({getOrThrow:()=> 'http://localhost:5173'}).overrideGuard(JwtAuthGuard).useValue({canActivate:(context:ExecutionContext)=>{const req=context.switchToHttp().getRequest();if(!req.headers['x-test-role'])return false;req.user={rol:{nombre:decodeURIComponent(req.headers['x-test-role'])}};return true;}}).compile();app=module.createNestApplication();configureApp(app,'http://localhost:5173');await app.init();});afterAll(async()=>{if(app)await app.close();});
 it.each(['Administrador','Operador / Técnico'])('POST autorizado %s',async role=>{await request(app.getHttpServer()).post('/drivers').set('x-test-role',encodeURIComponent(role)).send(values).expect(201);});
 it('rechaza rol, origen, valores y campo ajeno sin escribir',async()=>{await request(app.getHttpServer()).post('/drivers').set('x-test-role','Auditor Externo').send(values).expect(403);await request(app.getHttpServer()).post('/drivers').set('x-test-role','Administrador').set('Origin','https://evil.example').send(values).expect(403);await request(app.getHttpServer()).post('/drivers').set('x-test-role','Administrador').send({...values,estado:'DISPONIBLE'}).expect(400);expect(tx.conductor.create).not.toHaveBeenCalled();});
 it('GET y PATCH mantienen contrato',async()=>{await request(app.getHttpServer()).get('/drivers?page=2').set('x-test-role','Administrador').expect(200);await request(app.getHttpServer()).get('/drivers/'+id).set('x-test-role',encodeURIComponent('Operador / Técnico')).expect(200);await request(app.getHttpServer()).patch('/drivers/'+id).set('x-test-role','Administrador').send({estado:'INACTIVO'}).expect(200);});
});
