import { test, expect } from '@playwright/test';
const api = process.env.E2E_API_URL ?? 'http://localhost:3000';
for (const role of ['admin', 'operator'] as const) {
  test(`US-004: ${role} registra pedido; conserva borrador/foco y sesión/F5/logout`, async ({ page, context }) => {
    await page.route('https://tile.openstreetmap.org/**', route => route.fulfill({ status: 200, contentType: 'image/png', body: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jL2cAAAAASUVORK5CYII=', 'base64') }));
    const email = role === 'admin' ? process.env.E2E_LOGIN_EMAIL : process.env.E2E_OPERATOR_EMAIL;
    const password = role === 'admin' ? process.env.E2E_LOGIN_PASSWORD : process.env.E2E_OPERATOR_PASSWORD;
    if (!email || !password) throw new Error('Configura cuentas exclusivas E2E.');
    await page.goto('/login'); await page.getByLabel('Correo electrónico').fill(email); await page.getByLabel('Contraseña', { exact: true }).fill(password); await page.getByRole('button', { name: 'Iniciar sesión' }).click();
    await expect(page.getByRole('heading', { name: 'Acceso permitido' })).toBeVisible(); await page.getByRole('link', { name: 'Registrar pedido', exact: true }).click();
    await page.getByRole('button', { name: 'Registrar pedido', exact: true }).click(); await expect(page.getByText('Selecciona una prioridad permitida.')).toBeVisible();
    await page.getByLabel('Nombre del cliente').fill('Cliente E2E US-004'); await page.getByLabel('Dirección de entrega').fill('Destino E2E');
    await expect(page.getByLabel('Latitud', { exact: true })).toHaveCount(0); await expect(page.getByLabel('Longitud', { exact: true })).toHaveCount(0);
    await page.getByRole('region', { name: 'Mapa de ubicación de entrega' }).click();
    await expect(page.getByText('Punto de entrega seleccionado.', { exact: true })).toBeVisible();
    const marker = page.locator('.delivery-marker'); const box = await marker.boundingBox();
    if (!box) throw new Error('Marcador no visible');
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 25, box.y + box.height / 2 + 15, { steps: 5 }); await page.mouse.up();
    await page.getByLabel('Peso (kg)').fill('2.5');
    if (role === 'admin') await page.getByLabel('Volumen (m³) — opcional').fill('0.015');
    await page.getByLabel('Descripción de carga').fill('Costal de ropa'); await page.getByLabel('Referencia (opcional)').fill('Puerta azul');
    await page.getByLabel('Fecha de inicio').fill('2026-10-02'); await page.getByLabel('Hora de inicio').fill('09:00'); await page.getByLabel('Fecha de fin').fill('2026-10-02'); await page.getByLabel('Hora de fin').fill('11:00');
    await page.getByLabel('Prioridad', { exact: true }).selectOption('ESTANDAR'); await page.getByLabel('Tipo de producto').selectOption('NO_PERECEDERO');
    const identity = page.waitForResponse(r => r.url().endsWith('/auth/me') && r.status() === 200); await page.evaluate(() => window.dispatchEvent(new Event('focus'))); await identity;
    await expect(page.getByLabel('Nombre del cliente')).toHaveValue('Cliente E2E US-004');
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: test.info().outputPath('formulario-pedido.png'), fullPage: true });
    let requests = 0; let release!: () => void;
    const gate = new Promise<void>(resolve => { release = resolve; });
    await page.route('**/orders', async route => { requests++; await gate; await route.continue(); });
    const response = page.waitForResponse(r => r.url().endsWith('/orders') && r.request().method() === 'POST');
    await page.getByRole('button', { name: 'Registrar pedido', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Registrando pedido…' })).toBeDisabled();
    await page.getByRole('form').evaluate(form => { form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true })); }); release();
    const saved = await response; expect(saved.status()).toBe(201);
    const payload = saved.request().postDataJSON();
    expect(payload.ventana_inicio).toBe('2026-10-02T09:00:00-05:00'); expect(payload.ventana_fin).toBe('2026-10-02T11:00:00-05:00');
    expect(payload.volumen_m3).toBe(role === 'admin' ? 0.015 : null); expect(payload.descripcion_carga).toBe('Costal de ropa');
    expect(Number.isFinite(payload.cliente.latitud)).toBe(true); expect(Number.isFinite(payload.cliente.longitud)).toBe(true); expect(payload.cliente.referencia).toBe('Puerta azul');
    const body = await saved.json(); expect(body.volumen_m3).toBe(role === 'admin' ? '0.015' : null);
    await expect(page.getByText('Pedido registrado correctamente')).toBeVisible(); expect(requests).toBe(1);
    expect(await page.evaluate(() => localStorage.length + sessionStorage.length)).toBe(0);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: test.info().outputPath('registrar-pedido.png'), fullPage: true });
    await page.reload(); await expect(page.getByRole('form', { name: 'Registrar pedido' })).toBeVisible(); await expect(page.getByLabel('Nombre del cliente')).toHaveValue('');
    expect((await context.request.get(`${api}/auth/me`)).status()).toBe(200);
    await page.getByRole('button', { name: 'Cerrar sesión' }).click(); await expect(page).toHaveURL(/\/login$/); await page.goto('/pedidos/nuevo'); await expect(page).toHaveURL(/\/login$/);
  });
}
